### ISSUE TITLE
$ node build/index.js 卡住了

### ISSUE THREAD

**Issue by Xue-chuxin** [arnidan/nsfw-api#17]
![image](https://user-images.githubusercontent.com/69140474/180714076-007281a1-167a-4cd3-b4d5-d85d6e902964.png)
一直卡在这里应该怎么办？

**Comment by arnidan** [comment]
Hello,

I'm not responsible for `penndu/nsfw-api`. Try to use my image and report any issues according to it

**Comment by arnidan** [comment]
As I understood you already started the app, so just make a request just like in the [documentation](https://github.com/arnidan/nsfw-api#api-methods)
