### ISSUE TITLE
I had this problem when I started docker

### ISSUE THREAD

**Issue by OFFOM** [arnidan/nsfw-api#2]
yarn run v1.22.5
$ node build/index.js
Illegal instruction (core dumped)
error Command failed with exit code 132.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by arnidan** [comment]
Hi, 

There is the same problem in issue #1. 
Please, provide information about your system and processor type there. Also, try to build image manually

**Comment by OFFOM** [comment]
Hello, I've tried to run a new image, but it's still the same problem.

**Comment by arnidan** [comment]
OK, maybe you can try to start it on the local environment without docker?
Because, currently, I don't have access to any machine with x64 processor.

**Comment by OFFOM** [comment]
Hello, I installed the new Ubuntu 20.04 lts system and built the image manually. Now there are new problems. Here are new tips.
yarn run v1.22.18
$ node build/index.js
2022-05-20 02:57:47.424656: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

**Comment by arnidan** [comment]
Does api works?

**Comment by OFFOM** [comment]
I have tested that the API can be used normally.
