### ISSUE TITLE
https://s3.amazonaws.com/nsfwdetector/nsfwjs.zip Access Denied

### ISSUE THREAD

**Issue by penndu** [arnidan/nsfw-api#30]
![image](https://user-images.githubusercontent.com/46226528/195286904-b50be4ca-5b89-40b5-b9c4-0afa8b14e2fa.png)

**Comment by arnidan** [comment]
Hi, thanks for the issue

I just added models files to the project https://github.com/arnidan/nsfw-api/tree/master/model
