### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Mabisi** [arnidan/nsfw-api#37]
![image](https://user-images.githubusercontent.com/19968269/208266905-f0d49af3-a57d-454b-bc79-b7b6870f3bf4.png)

**Comment by arnidan** [comment]
Hello, sorry for the delay.

What exactly did you do? I just tried to run the image from `ghcr.io/arnidan/nsfw-api:latest` and it works.

**Comment by Mabisi** [comment]
> Hello, sorry for the delay.
> 
> What exactly did you do? I just tried to run the image from `ghcr.io/arnidan/nsfw-api:latest` and it works.

Already solved! Thanks for the reply
