### ISSUE TITLE
model.json does not exis

### ISSUE THREAD

**Issue by qiin** [arnidan/nsfw-api#48]
Hello, friend:
After running, post requests prompts：
Error: Path /model/model.json does not exist: loading failed<br> &nbsp; &nbsp;at /node_modules/@tensorflow/tfjs-node/dist/io/file_system.js:67:23

docker-compose.yml Already added It's the same，Can you give me some guidance.

**Comment by arnidan** [comment]
Hello, I just pushed the fix. Try to run the updated image.

If you'll get the error again, please, reopen the issue
