### ISSUE TITLE
[Feature request] A more light-weighted model

### ISSUE THREAD

**Issue by fkcptlst** [arnidan/nsfw-api#49]
Maybe add some optional light-weighted models to choose from? After all, Inception is a bit too heavy for small servers. Its memory consumption is too large.

**Comment by arnidan** [comment]
Hello @fkcptlst, thank you for the great idea!

Could you check `docker pull ghcr.io/arnidan/nsfw-api:50_merge-min` image on your environment?
It's bundled with quantized model

**Comment by arnidan** [comment]
I made some tests. 
Seems like there is no big difference in RAM usage between the models. It's saving around 50MB, 600MB (default) vs 650MB (min)

**Comment by fkcptlst** [comment]
Yes, my test results are the same. It turns out that the Inception sometimes even consumes less RAM than MobileNet, which is a bit peculiar.

Thanks for the effort!
